//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 06:11:56 AM VET 
//


package com.larionov.epam.entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for categoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="categoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subCategory" type="{}subCategoryType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sign" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "categoryType", propOrder = {
    "subCategory"
})
public class CategoryType {

    @XmlElement(required = true)
    protected SubCategoryType subCategory;
    @XmlAttribute
    protected String sign;

    /**
     * Gets the value of the subCategory property.
     * 
     * @return
     *     possible object is
     *     {@link SubCategoryType }
     *     
     */
    public SubCategoryType getSubCategory() {
        return subCategory;
    }

    /**
     * Sets the value of the subCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubCategoryType }
     *     
     */
    public void setSubCategory(SubCategoryType value) {
        this.subCategory = value;
    }

    /**
     * Gets the value of the sign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSign() {
        return sign;
    }

    /**
     * Sets the value of the sign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSign(String value) {
        this.sign = value;
    }

    @Override
    public String toString() {
        return "CategoryType{" +
                "subCategory=" + subCategory +
                ", sign='" + sign + '\'' +
                '}';
    }
}
